name: tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stub-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        laravel: [11]

    name: Test Stubs - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:^${{ matrix.laravel }} .
          composer require cuonggt/trecms:@dev --no-interaction --no-update
          composer config repositories.trecms '{"type": "path", "url": "trecms"}' --file composer.json

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'trecms'

      - name: Install Breeze
        run: |
          composer update "laravel/trecms" --prefer-dist --no-interaction --no-progress -W
          php artisan trecms:install

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
